// <auto-generated />
using System;
using Databases.RetrieverCore.LocalDatabase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Databases.RetrieverCore.LocalDatabase.Migrations
{
    [DbContext(typeof(LocalDatabaseContext))]
    [Migration("20200731154059_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.BatteryEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerEntityID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxWearLevel")
                        .HasColumnType("REAL");

                    b.Property<string>("Vendor")
                        .HasColumnType("TEXT");

                    b.Property<double>("Voltage")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("ComputerEntityID");

                    b.ToTable("Batteries");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.ComputerEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MainboardID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("MainboardID");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.DDREntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clocking")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerEntityID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ComputerEntityID");

                    b.ToTable("DDRs");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.GPUEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerEntityID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<double>("MemorySize")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScreenHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScreenWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ComputerEntityID");

                    b.ToTable("GPUs");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.MainboardEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Socket")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Mainboards");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.MainboardPortEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MainboardEntityID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("MainboardEntityID");

                    b.ToTable("MainboardPorts");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.NetworkInterfaceEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerEntityID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ComputerEntityID");

                    b.ToTable("NetworkInterfaces");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.ProcessorEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Architecture")
                        .HasColumnType("TEXT");

                    b.Property<double>("ClockSpeed")
                        .HasColumnType("REAL");

                    b.Property<byte>("Cores")
                        .HasColumnType("INTEGER");

                    b.Property<double>("L2CacheSize")
                        .HasColumnType("REAL");

                    b.Property<double>("L3CacheSize")
                        .HasColumnType("REAL");

                    b.Property<byte>("LogicalProcessor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MainboardEntityID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Socket")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("MainboardEntityID");

                    b.ToTable("Processors");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.StorageEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComputerEntityID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ComputerEntityID");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.BatteryEntity", b =>
                {
                    b.HasOne("RetrieverCore.LocalDatabase.Models.ComputerEntity", null)
                        .WithMany("Batteries")
                        .HasForeignKey("ComputerEntityID");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.ComputerEntity", b =>
                {
                    b.HasOne("RetrieverCore.LocalDatabase.Models.MainboardEntity", "Mainboard")
                        .WithMany()
                        .HasForeignKey("MainboardID");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.DDREntity", b =>
                {
                    b.HasOne("RetrieverCore.LocalDatabase.Models.ComputerEntity", null)
                        .WithMany("DDRs")
                        .HasForeignKey("ComputerEntityID");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.GPUEntity", b =>
                {
                    b.HasOne("RetrieverCore.LocalDatabase.Models.ComputerEntity", null)
                        .WithMany("GPUs")
                        .HasForeignKey("ComputerEntityID");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.MainboardPortEntity", b =>
                {
                    b.HasOne("RetrieverCore.LocalDatabase.Models.MainboardEntity", null)
                        .WithMany("MainboardPorts")
                        .HasForeignKey("MainboardEntityID");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.NetworkInterfaceEntity", b =>
                {
                    b.HasOne("RetrieverCore.LocalDatabase.Models.ComputerEntity", null)
                        .WithMany("NetworkInterfaces")
                        .HasForeignKey("ComputerEntityID");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.ProcessorEntity", b =>
                {
                    b.HasOne("RetrieverCore.LocalDatabase.Models.MainboardEntity", null)
                        .WithMany("Processors")
                        .HasForeignKey("MainboardEntityID");
                });

            modelBuilder.Entity("RetrieverCore.LocalDatabase.Models.StorageEntity", b =>
                {
                    b.HasOne("RetrieverCore.LocalDatabase.Models.ComputerEntity", null)
                        .WithMany("Storages")
                        .HasForeignKey("ComputerEntityID");
                });
#pragma warning restore 612, 618
        }
    }
}
